Feature/starting over
ditrit/verdeter pull request #3
Opened 2022-09-02 13:08 UTC by slashformotion

- Keep the same API (almost, some functions were renamed)
- Remove old code and code specific to badaas

2022-09-02 14:02 UTC, Zorin95670 requested changes

2022-09-02 14:02 UTC, Zorin95670 commented on go.mod
> +module github.com/ditrit/verdeter
put this commit before code commit :)

2022-09-02 14:02 UTC, Zorin95670 commented on README.md
> +    *Example:* let's say thay we **did not** call (*VerdeterCommand).SetRequired("time")` to set the key "time" as required.
missing ` before (*VerdeterCommand).SetRequired("time")

2022-09-05 08:56 UTC, slashformotion commented
qsd

2022-09-06 08:02 UTC, Zorin95670 requested changes

2022-09-06 08:02 UTC, Zorin95670 commented on io.go
> +func FileExist(path string) bool {
missing unit test

2022-09-06 13:54 UTC, Zorin95670 approved these changes

2022-09-06 13:55 UTC, merged